SENSORS = {
"12.0.49.1":     ["temp", "Aeon Labs",  "ff00ff", "Old_hallway_f2", "Temperature"],
"12.0.49.3":     ["lmns", "Aeon Labs",  "ff00ff", "Old_hallway_f2", "Luminiscence"],
"12.0.49.5":     ["humi", "Aeon Labs",  "ff00ff", "Old_hallway_f2", "Humidity"],
"12.0.49.27":    [None,   "Aeon Labs",  "ff00ff", "Old_hallway_f2", "Ultraviolet"],
"12.0.113.7.3":  [None,   "Aeon Labs",  "ff00ff", "Old_hallway_f2", "Burglar Alarm"],
"13.0":          ["lgts", "Fibar Group","0000ff", "Kitchen", "Switch"],
"18.0.49.1":     ["temp", "Z-Wave.Me",  "0088ff", "Outside_in_sun", "Temperature"],
"18.0.49.3":     ["lmns", "Z-Wave.Me",  "0088ff", "Outside_in_sun", "Luminiscence"],
"18.0.49.5":     ["humi", "Z-Wave.Me",  "0088ff", "Outside_in_sun", "Humidity"],
"18.0.49.6":     ["wthr", "Z-Wave.Me",  "ff0000", "Wind_speed", "Velocity"],
"18.0.49.9":     ["wthr", "Z-Wave.Me",  "0000ff", "Barometer", "Barometric Pressure"],
"18.0.49.11":    ["temp", "Z-Wave.Me",  "0000ff", "Dew_Point_in_sun", "Dew Point"],
"18.0":          [None,   "Z-Wave.Me",  "0000ff", "Wind Meter", "Battery"],
"19.0.49.1":     ["temp", "Fibar Group","00ffff", "New_hallway_f2", "Temperature"],
"19.0.113.1.2":  [None,   "Fibar Group","00ffff", "New_hallway_f2", "Smoke Alarm"],
"19.0.113.4.2":  [None,   "Fibar Group","00ffff", "New_hallway_f2", "Heat Alarm"],
"19.0":          [None,   "Fibar Group","00ffff", "New_hallway_f2", "Battery"],
"130.0.49.1":    ["temp", "Aeon Labs",  "ff0000", "Kitchen", "Temperature"],
"130.0.49.3":    ["lmns", "Aeon Labs",  "ff0000", "Kitchen", "Luminiscence"],
"130.0.49.5":    ["humi", "Aeon Labs",  "ff0000", "Kitchen", "Humidity"],
"130.0.49.27":   [None,   "Aeon Labs",  "ff0000", "Kitchen", "Ultraviolet"],
"130.0.113.7.3": [None,   "Aeon Labs",  "ff0000", "Kitchen", "Burglar Alarm"],
"133.0":         ["lgts", "Domi LightB","0000ff", "Old_hallway_f2", "Dimmer"],
"134.0":         ["lgts", "Nodon",      "0000ff", "Living_room", "Switch"],
}

RRD_DEFS = {
        "temp": { 'name': "Temperature", 'file': "temp",
            'vertical-label': "C"},
        "humi": { 'name': "Humidity", 'file': "humidity",
            'vertical-label': "%"},
        "wthr": { 'name': "Weather", 'file': "weather",
            'vertical-label': "m/s"},
        "lgts": { 'name': "Lights", 'file': "light_status",
            'vertical-label': "On/Off"},
        "lmns": { 'name': "Brightness", 'file': "luminescence",
            'vertical-label': "lm"}
}
